Releases version
plus3it/spel pull request #419
Opened 2020-09-22 20:28 UTC by justinorrplus3it

Fixes # .

Changes offered/proposed in this pull request:
- 
- 
- 

* New PR Alert to: @plus3it/spel

2020-09-22 20:42 UTC, eemperor requested changes
You need to add the manifest files and also run bumpversion to update the version

2020-09-22 20:42 UTC, eemperor commented on CHANGELOG.md
> +**Commit Delta**: [Change from 2020.07.1 release](http://github.com/plus3it/spel/compare/2020.08.1...2020.09.1)
Change from version should be `2020.08.1`

```suggestion
**Commit Delta**: [Change from 2020.08.1 release](http://github.com/plus3it/spel/compare/2020.08.1...2020.09.1)
```

2020-09-22 20:42 UTC, eemperor commented on CHANGELOG.md
> +**Manifests**: <https://github.com/plus3it/spel/blob/2020.09.rc1.1/manifests>
Remove `rc1`

```suggestion
**Manifests**: <https://github.com/plus3it/spel/blob/2020.09.1/manifests>
```

2020-09-22 20:46 UTC, eemperor commented
The PR title and commit message should also have the version number.

`Releases version 2020.09.1`

2020-09-22 20:54 UTC, lorengordon commented
@justinorrplus3it for comparison, here is the pr for the last release: https://github.com/plus3it/spel/pull/415/files

2020-09-23 21:22 UTC, eemperor requested changes

2020-09-23 21:22 UTC, eemperor commented on CHANGELOG.md
> +### 2020.09.1
Minor nitpick.  Add line before version heading.

```suggestion

### 2020.09.1
```

2020-09-23 21:24 UTC, lorengordon requested changes
There's something going on with the submodule that is not supposed to be here. Please do not merge until we get that fixed. Go ahead and make any changes to the pr, then I'll fix it up.

2020-09-23 21:30 UTC, eemperor commented
Weird.  Thought it was cleaned up.

2020-09-24 00:28 UTC, lorengordon approved these changes
Looks good now, thanks!

2020-09-24 00:39 UTC, eemperor approved these changes

2020-09-24 00:39 UTC, merged